### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by chehe040** [SoftTech-Global/Perfect-Resume#33]
Hi, I was going through README.md and found out that links to these 2 files are invalid.

I would like to work on this issue and add 
**Contributing.md** and **CODE_OF_CONDUCT.md** to this project

![image](https://user-images.githubusercontent.com/88290551/194691939-453814bf-819e-4937-b04b-de02502c5513.png)

Please assign me this issue so I can work on it.

**Comment by mrsaifullah52** [comment]
Hey, issue assigned. Now you can contribute to this project
